### ISSUE TITLE
Shorebird Discord is missing a "to the code machine" sticker

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/old_repo#1]
It's very important.  So important it's our first ever issue on GitHub.

This is very promising:
![to_the_code_machine](https://user-images.githubusercontent.com/478541/219441299-eb073d60-35ba-4303-99b2-13058fbcb3f3.gif)

But is above the 512k limit for Discord stickers.  All is lost.

@sethladd says he knows the 🧙‍♂️ magic to make things right in the world.

**Comment by eseidel** [comment]
Turns out it needs to be apng or png too.  I looked briefly. :)

**Comment by sethladd** [comment]
I feel like my whole life has lead up to this moment.

Also, I think I need to be a server admin? I need to get into Server Settings. Is that something you can share, until I figure this out for you? Then you can revoke the permissions, no problem.

**Comment by sethladd** [comment]
I'm also unable to assign this issue to me, feel free to assign it.

**Comment by sethladd** [comment]
OK, give it a shot! I've uploaded the sticker.

**Comment by eseidel** [comment]
Huzzah!
